### ISSUE TITLE
Error in correlation calculation for residue-pairs

### ISSUE THREAD

**Issue by zhenglz** [RUBi-ZA/MD-TASK#29] opened 2020-02-11 11:00 UTC
I used the following command for calculating DCC for a trajectory:

python ~/MD-TASK/calc_correlation.py --trajectory fit_traj_center_noH_9.xtc --topology npt_rest.pdb --step 50 --prefix dcc_

The following error was reported:

> INFO::Started at: 2020-02-11 18:56:27.691651
INFO::Preparing a trajectory matrix...
INFO::Correlating...
Traceback (most recent call last):
  File "\~/MD-TASK/calc_correlation.py", line 164, in <module>
    CLI(parser, main, log)
  File "\~/MD-TASK/lib/cli.py", line 20, in CLI
    callback(args)
  File "\~/MD-TASK/calc_correlation.py", line 141, in main
    correlation = correlate(traj_matrix)
  File "\~/MD-TASK/calc_correlation.py", line 76, in correlate
    jdelta = resJ - meanJ
ValueError: operands could not be broadcast together with shapes (1002,3) (501,3)

Please indicate how to fix this? Thanks a lot!

**Comment by zhenglz** [comment] 2020-02-11 11:25
Possibly I have identified an issue in the code (calc_correlation.py) line 59

num_trajectories = len(residues[sorted_residues[0]])

The number of trajectories may not be the number of frames? I just set this value to one, since I have only one trajectory. 

After this modification, no error was reported.

**Comment by oliserand** [comment] 2020-02-13 17:47
Hi zhenglz,
Can you please send us an example data so that we can reproduce the error? 
Thanks for using MD-TASK!

**Comment by jjmadsen** [comment] 2021-02-03 20:41
Hi  @oliserand 

Any update on this issue? I am running into the same problem...
@zhenglz were you able to verify your results after manually changing the num_trajectories variable? Is this a workable fix?

Thanks!
Jesper

**Comment by oliserand** [comment] 2021-02-03 20:48
Hi @jjmadsen , we're actually working on updating the tools. We'll let you know asap.

**Comment by jjmadsen** [comment] 2021-02-03 21:01
@oliserand terrific

**Comment by oliserand** [comment] 2021-02-03 21:33
@jjmadsen , you could try the same tool on our [web server](https://mdmtaskweb.rubi.ru.ac.za/#dcc) in the mean time.

**Comment by oliserand** [comment] 2021-09-12 04:26
The reported bug looks like a known issue, which has been fixed in the MDM-TASK-web / MDM-TASK-dev branches

**Closed as completed** 2021-09-12 04:26 UTC
